# Markdown Linting Configuration
# See https://github.com/DavidAnson/markdownlint for rule details

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013: false  # Disabled - don't enforce line length

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - br
    - antml:function_calls
    - antml:invoke
    - antml:parameter

# MD041/first-line-heading - First line in file should be a top level heading
MD041: false  # Allow flexibility for files that start with YAML frontmatter or comments

# MD046/code-block-style - Code block style
MD046:
  style: fenced

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true  # Allow same heading in different sections

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 2

